{% set name = "delabella" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/msokalski/delabella/archive/V{{ version }}.tar.gz
  sha256: 2f3a2b34a7a1e2cbe43cb6b7c1bdef42cec9d508c3e3129878e304a08fab72aa
  patches:
    - 0001-Missing-include.patch
    - 0002-Shared-library.patch
    - 0003-pkgconfig.patch
    - 0004-OSX-gettime.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake  >=3.15
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/share/pkgconfig/delabella.pc                       # [unix]
    - test -f $PREFIX/include/delabella.h                                # [unix]
    - if not exist %PREFIX%\\Library\\include\\delabella.h (exit 1)      # [win]

about:
  home: https://github.com/msokalski/delabella
  summary: '2D Delaunay triangulation (dela) - super stable (bella!) '
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/msokalski/delabella

extra:
  recipe-maintainers:
    - martinRenou
